Repository open-mmlab/mmrazor, pull requests merged in 2022-03, with the labels that each got.

#87 [Docs] Add Algorithm Metafiles
  configs/distill/cwd/metafile.yml
  configs/distill/wsld/metafile.yml
  configs/nas/darts/metafile.yml
  configs/nas/detnas/metafile.yml
  configs/nas/spos/metafile.yml
  configs/pruning/autoslim/metafile.yml
  model-index.yml
Labels: documentation

#82 [FEATURE] Mobilenet Series Search Space
  configs/nas/spos/README.md
  configs/nas/spos/SPOS_MOBILENET_490M_FROM_ANGELNAS.yaml
  configs/nas/spos/spos_evolution_search_mobilenet_proxyless_gpu_flops465_8xb512_in1k.py
  configs/nas/spos/spos_mobilenet_for_check_ckpt_from_anglenas.py
  configs/nas/spos/spos_subnet_mobilenet_proxyless_gpu_8xb128_in1k.py
  configs/nas/spos/spos_supernet_mobilenet_proxyless_gpu_8xb128_in1k.py
  mmrazor/models/architectures/components/backbones/__init__.py
  mmrazor/models/architectures/components/backbones/searchable_mobilenet.py
  mmrazor/models/ops/__init__.py
  mmrazor/models/ops/common.py
  mmrazor/models/ops/mobilenet_series.py
  tests/test_models/test_algorithms/test_algorithm.py
  tests/test_models/test_op.py
Labels: enhancement

#102 [Feature] Add function to meet mmdeploy support
  mmrazor/apis/mmcls/__init__.py
  mmrazor/apis/mmcls/inference.py
  mmrazor/apis/mmdet/__init__.py
  mmrazor/apis/mmdet/inference.py
  mmrazor/apis/mmseg/__init__.py
  mmrazor/apis/mmseg/inference.py
  tests/test_apis/test_inference.py
Labels: enhancement

#104 [Refactor] Delete redundant `set_random_seed` function
  mmrazor/apis/__init__.py
  mmrazor/apis/mmcls/__init__.py
  mmrazor/apis/mmcls/train.py
  mmrazor/apis/mmdet/__init__.py
  mmrazor/apis/mmdet/train.py
  mmrazor/apis/mmseg/__init__.py
  mmrazor/apis/mmseg/train.py
  mmrazor/apis/utils.py
  tests/deprecated_api/test_remove_0-5.py
  tests/test_apis/test_inference.py
  tests/test_apis/test_utils.py
  tools/mmcls/train_mmcls.py
  tools/mmdet/train_mmdet.py
  tools/mmseg/train_mmseg.py
Labels: refactoring
