Repository open-mmlab/mmrazor, pull requests merged in 2022-02, with the labels that each got.

#90 [FIX] Fix slurm search shell scripts
  tools/mmcls/slurm_search_mmcls.sh
Labels: Bug:P3

#95 [CI] Add CI for windows and redesign CI
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: CI

#93 [CI] update pre-commit-config
  .pre-commit-config.yaml
Labels: documentation, CI
