Repository open-mmlab/mmrazor, pull requests merged in 2022-01, with the labels that each got.

#41 [Fix] Fix symlink error on windows
  .gitignore
  setup.py
Labels: Installation

#51 [Docs] Fix some unconsistency
  configs/_base_/datasets/mmcls/imagenet_bs128_colorjittor.py
  configs/nas/detnas/README.md
  configs/nas/detnas/detnas_evolution_search_frcnn_shufflenetv2_fpn_coco.py
  configs/nas/detnas/detnas_subnet_shufflenetv2_8xb128_in1k.py
  configs/nas/detnas/detnas_supernet_shufflenetv2_8xb128_in1k.py
  configs/nas/spos/README.md
  configs/nas/spos/spos_evolution_search_shufflenetv2_8xb2048_in1k.py
  configs/nas/spos/spos_subnet_shufflenetv2_8xb128_in1k.py
  configs/nas/spos/spos_supernet_shufflenetv2_8xb128_in1k.py
Labels: documentation

#53 [Fix] Fix `show_result` error during test
  tools/mmcls/search_mmcls.py
  tools/mmcls/test_mmcls.py
  tools/mmdet/search_mmdet.py
  tools/mmdet/test_mmdet.py
  tools/mmseg/test_mmseg.py
Labels: bug

#58 [Docs] Add OpenMMLab website and platform links and mmdeploy link
  README.md
  README_zh-CN.md
Labels: documentation

#63 [Fix] Fix bug in non-distributed training/testing for all tasks
  tools/mmcls/test_mmcls.py
  tools/mmcls/train_mmcls.py
  tools/mmdet/test_mmdet.py
  tools/mmdet/train_mmdet.py
  tools/mmseg/test_mmseg.py
  tools/mmseg/train_mmseg.py
Labels: upstream issue

#59 [Enhance] Add setup multi-processes for all tasks
  docs/en/api.rst
  docs/zh_cn/api.rst
  mmrazor/utils/__init__.py
  mmrazor/utils/setup_env.py
  setup.cfg
  tests/test_utils/test_setup_env.py
  tools/mmcls/search_mmcls.py
  tools/mmcls/test_mmcls.py
  tools/mmcls/train_mmcls.py
  tools/mmdet/search_mmdet.py
  tools/mmdet/test_mmdet.py
  tools/mmdet/train_mmdet.py
  tools/mmseg/test_mmseg.py
  tools/mmseg/train_mmseg.py
Labels: documentation, enhancement
